### PR TITLE
Make plone5 compatible, fix tests, integrate travis, deprecate Plone < 4.3

### LINKED ISSUE #4: Exception when running tests
```python
Module: collective.contentrules.comingsoon.tests

Traceback (most recent call last):
  File "/home/rodfersou/.projects/collective.contentrules.comingsoon/collective/contentrules/comingsoon/tests.py", line 7, in <module>
    from Products.PloneTestCase import PloneTestCase as ptc
ImportError: No module named PloneTestCase
```

### PR DESCRIPTION
**Pull request by rodfersou**
Review package prior to implementing new features:

 - add .gitignore file
 - fix tests
 - integrate travis CI
 - update readme/history
 - Closes #4

### CODE REVIEW

**Comment by rodfersou** [comment]
@instification fixed somethings in the package, but the tests are failing for Plone 5.x (something related with mailhost notification), if you have some glue on it, please help (we need to make it work for Plone 5, right?)

**Comment by instification** [comment]
@rodfersou I had a similar problem with tests on another package -  see https://github.com/collective/redomino.tokenrole/pull/17/commits/1e2670c1e39412988b13a6b7ac1e97ed9ecc1ac4

It looks like they are handling outbound mail slightly differently in the current tests here though, by creating a mock mail host.

I think the problem is that the way you set up the mail settings is different between plone 4 and 5, so the mail sending fails because there's no smtp/from settings etc. The commit above shows how to set them based on version. I would start there and see if it fixes it.

**Comment by rodfersou** [comment]
@instification I did the exact same setup, but the tests still don't work here

**Comment by rodfersou** [comment]
@instification in fact got worse my changes.. for Plone 4.3 it was working before..

**Comment by instification** [comment]
@thet @macagua @cedricmessiant @toutpt @tdesvenain

Is anybody still maintaining this package? Are we ok to merge this PR? We would like to make a feature PR and fix other bugs, so we would like the tests/CI to be merged first.

**Review by instification — APPROVED** [review]

**Pull request merged**
